AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  products-microservice

  Sample SAM Template for products-microservice

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 6

Resources:
  ProductsTable:
    Type: "AWS::Serverless::SimpleTable"
    Properties:
      TableName: ProductsTable
      PrimaryKey:
        Name: id
        Type: String

  ProductsMicroserviceFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: products-microservice/
      Handler: app.handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        ProductsAPI:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
